export const SET_LOADER = "SET_LOADER";
export const CLOSE_LOADER = 'CLOSE_LOADER';
export const SET_UPDATE_PROFILE_ERRORS = 'SET_UPDATE_PROFILE';
export const REMOVE_UPDATE_PROFILE_ERRORS = 'REMOVE_UPDATE_PROFILE';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const REMOVE_SUCCESS_MESSAGE = 'REMOVE_SUCCESS_MESSAGE';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERRORS = 'UPDATE_PASSWORD_ERRORS';

export const REMOVE_UPDATE_PASSWORD_SUCCESS = 'REMOVE_UPDATE_PASSWORD_SUCCESS';
export const REMOVE_UPDATE_PASSWORD_ERRORS = 'REMOVE_UPDATE_PASSWORD_ERRORS';

